name: ng_infinite_scroll
version: 0.2.0
description: >
  Infinite Scrolling for AngularDart
author: Juha Komulainen <juha.komulainen@evident.fi>
homepage: https://bitbucket.org/evidentsolutions/dart-ng-infinite-scroll
dependencies:
  angular: ">=1.0.0 <2.0.0"
